initialization
registerClassInfos

	self addMessageToClass: 'CLASS1' withName: 'MESSAGE11' withInfo: 'INFO TO MESSAGE11'.
	self addMessageToClass: 'CLASS1' withName: 'MESSAGE12' withInfo: 'INFO TO MESSAGE12'.
	self addMessageToClass: 'CLASS2' withName: 'MESSAGE21' withInfo: 'INFO TO MESSAGE21'.
	self addMessageToClass: 'CLASS2' withName: 'MESSAGE22' withInfo: 'INFO TO MESSAGE22'.
	self addMessageToClass: 'CLASS2' withName: 'MESSAGE23' withInfo: 'INFO TO MESSAGE23'